import { registerUserController,loginUserController } from "../controllers/auth_controller";
import  express  from "express";
import { saveNewPasswordController, validateEmailController, validateOTPController } from "../controllers/change_password_controller";
import { getUserDataController } from "../controllers/get_user_data_controller";
import { storeUserLocationController } from "../controllers/store_user_location_controller";
import { changeUsernameController } from "../controllers/change_user_name_controller";
import { uploadHouseController } from "../controllers/upload_house_controller";
import { getNearbyHousesController } from "../controllers/nearby_house_controller";
import { upload } from "../utils/multer";
import { getHotDealsController } from "../controllers/get_hot_deals_controller";
import { addToWishListController,getWishlistController,checkWishlistStatusController } from "../controllers/wishlist_controller";
import { addReviewController,getReviewsController,getAverageRatingController,checkReviewStatusController } from "../controllers/review_controller";
import { getRecommendedHousesController } from "../controllers/recommended_controller";
import { searchHousesController } from "../controllers/search_controller";
import { addToRentsController,getRentsController } from "../controllers/my_rents_controller";
import { getMyHousesController } from "../controllers/my_houses_controller";
import { changeLandlordController } from "../controllers/assign_landlord_controller";
import { uploadProfilePicController,getProfilePicController } from "../controllers/upload_profilepic_controller";
import { confirmPaymentController,createPaymentIntentController,getBookingStatusController } from "../controllers/payment_controller";
import { updateHouseController,deleteHouseController } from "../controllers/upload_house_controller";
import {createLandlordRequestController,getAllLandlordRequestsController,approveLandlordRequestController,rejectLandlordRequestController} from "../controllers/landlord_request_controller";
import { createAdminController } from "../controllers/create_admin_controller";

const router=express.Router();

router.post('/registerUser',registerUserController);
router.post('/loginUser',loginUserController);
router.post('/validateEmail',validateEmailController);
router.post('/validateOTP',validateOTPController);
router.post('/changePassword',saveNewPasswordController);
router.post('/getUsername',getUserDataController);
router.post('/storeUserLocation',storeUserLocationController);
router.post('/changeName',changeUsernameController);
router.post("/uploadHouse", upload.single("image"), uploadHouseController);
router.get('/nearbyHouses/:latitude/:longitude', getNearbyHousesController);
router.get('/hotDeals',getHotDealsController);
router.post("/addWishlist", addToWishListController);
router.get("/getWishlist/:userEmail", getWishlistController);
router.get("/checkWishlist/:userEmail/:houseId", checkWishlistStatusController);
router.post("/addReview", addReviewController);
router.get("/getReviews/:houseId", getReviewsController);
router.get("/getAverageRating/:houseId", getAverageRatingController);
router.get("/checkReview/:houseId/:tenantEmail", checkReviewStatusController);
router.get("/recommendedHouses", getRecommendedHousesController);
router.get("/searchHouses", searchHousesController);
router.post("/addRent", addToRentsController);
router.get("/getRents/:userEmail", getRentsController);
router.get("/myHouses/:landlordEmail", getMyHousesController);
router.post("/changeRole",changeLandlordController);
router.post("/uploadProfilePic", upload.single("image"), uploadProfilePicController);
router.get("/getProfilePic/:email", getProfilePicController);
router.post("/createPaymentIntent", createPaymentIntentController);
router.post("/confirmPayment", confirmPaymentController);
router.get("/getBookingStatus/:houseId", getBookingStatusController);
router.post("/updateHouse", updateHouseController);
router.delete("/deleteHouse/:houseId", deleteHouseController);
router.post("/landlord/request",upload.single("citizenship"),createLandlordRequestController);
router.get("/admin/landlordRequests",getAllLandlordRequestsController);
router.post("/admin/approveLandlord/:id",approveLandlordRequestController);
router.post("/admin/rejectLandlord/:id",rejectLandlordRequestController);
router.post("/admin/create", createAdminController);

export default router;